import FAQItem from "@/components/FAQItem";

export const metadata = {
  title: "FAQ — Bazi Bliss",
  description: "Frequently asked questions about Bazi, our reports, and how it all works.",
};

const faqs = [
  {
    question: "What is Bazi?",
    answer:
      "Bazi, also known as the Four Pillars of Destiny, is an ancient Chinese system of personality and destiny analysis based on your birth date and time. Think of it as a 'life blueprint' that reveals your natural tendencies, strengths, challenges, and the rhythm of opportunities throughout your life. It's been practiced for over 1,000 years.",
  },
  {
    question: "How is Bazi different from Western astrology?",
    answer:
      "Western astrology is based on planetary positions at your birth and focuses on sun signs, moon signs, and rising signs. Bazi is based on the Five Elements (Wood, Fire, Earth, Metal, Water) and the interactions between them. Bazi also maps your luck cycles in 10-year periods, giving you a timeline of when different energies are active in your life. Many people find Bazi more specific and actionable than Western astrology.",
  },
  {
    question: "How is my Life Blueprint generated?",
    answer:
      "Your Life Blueprint is generated by an advanced AI model trained on thousands of authentic Bazi readings and classical texts. The AI calculates your birth chart (Four Pillars), analyzes the Five Element balance, identifies your Day Master (core energy type), maps your 10-year luck cycles, and synthesizes everything into a comprehensive, personalized report written in natural English. Every report is reviewed before delivery to ensure quality and positive framing.",
  },
  {
    question: "What information do I need to provide?",
    answer:
      "You'll need your birth date (day, month, year), your birth time (as precise as possible — even an estimate helps), and the city where you were born. The birth time is used for accurate chart calculation, as the Bazi system divides each day into 12 two-hour periods. If you don't know your exact birth time, select 'Unknown' and we'll use noon as a default.",
  },
  {
    question: "What if I don't know my exact birth time?",
    answer:
      "No problem. Select 'Unknown' on the order form and we'll use noon (12:00 PM) as the default birth time. While knowing the exact time gives the most precise reading, a noon-default chart still provides accurate and valuable insights. Many of our customers don't know their exact birth time and still find their reports deeply meaningful.",
  },
  {
    question: "How long does it take to receive my report?",
    answer:
      "Your report is typically delivered to your email within 24 hours of purchase. Most reports are delivered much sooner — often within a few hours. You'll receive a confirmation email right after purchase, and the full PDF report will follow.",
  },
  {
    question: "Is this fortune telling? Will it predict my exact future?",
    answer:
      "Bazi is not fortune telling in the traditional sense. It does not predict lottery numbers or exact events. Instead, it reveals your inherent tendencies, the energetic patterns that influence different periods of your life, and the types of opportunities and challenges you're likely to encounter. Think of it as a weather forecast for your life — it tells you when the conditions are favorable for certain activities, but you're always the one making choices. Your chart shows tendencies, not destiny.",
  },
  {
    question: "Can I get a refund?",
    answer:
      "Due to the personalized and digital nature of our reports, we do not offer automatic refunds. However, if you're genuinely unsatisfied with your report, please reach out to us within 7 days of delivery and we'll work with you to make it right — whether that means revising your report or issuing a refund on a case-by-case basis.",
  },
  {
    question: "What makes this different from other astrology apps?",
    answer:
      "Most astrology apps give you generic, automated blurbs based on your sun sign. Bazi Bliss produces a deeply personalized, 8000-word report based on your exact birth date, time, and location — analyzed through a system that's been refined over a millennium. We use AI to generate the report but human oversight to ensure quality, accuracy, and a genuinely helpful, empowering tone.",
  },
  {
    question: "Do I need to know anything about Chinese culture?",
    answer:
      "Not at all. Your report is written in clear, modern English with all concepts explained in relatable terms. We translate the traditional terminology into practical insights you can actually use. If you're curious about the underlying system, our blog has plenty of introductory articles.",
  },
  {
    question: "Will you share or sell my birth data?",
    answer:
      "Never. Your birth information and email are used solely to generate your report and communicate with you about your order. We do not sell, share, or use your data for any other purpose. You can request deletion of your data at any time by emailing us.",
  },
  {
    question: "Can I ask a follow-up question after receiving my report?",
    answer:
      "Yes! Annual Pass customers get one free follow-up question. For other products, you can purchase a follow-up by contacting us. We're also happy to clarify anything in your report — just reply to your delivery email.",
  },
];

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-[#0f0f0f]">
      <div className="max-w-2xl mx-auto px-4 py-16">
        <h1 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] text-center mb-3">
          Frequently Asked Questions
        </h1>
        <p className="text-[#9c9588] text-center mb-12">
          Everything you need to know about Bazi and our reports.
        </p>
        <div className="bg-[#1a1a1a] rounded-2xl border border-[#2a2a2a] px-6 py-2">
          {faqs.map((faq, i) => (
            <FAQItem key={i} {...faq} />
          ))}
        </div>
      </div>
    </div>
  );
}
