import Link from "next/link";
import ProductCards from "@/components/ProductCards";
import FAQItem from "@/components/FAQItem";
import TestimonialCard from "@/components/TestimonialCard";

const faqs = [
  {
    question: "What is Bazi?",
    answer:
      "Bazi, also known as the Four Pillars of Destiny, is an ancient Chinese system of personality and destiny analysis based on your birth date and time. Think of it as a 'life blueprint' that reveals your natural tendencies, strengths, challenges, and the rhythm of opportunities throughout your life. It's been practiced for over 1,000 years and is now enhanced by AI to make it accessible to everyone.",
  },
  {
    question: "How is my Life Blueprint generated?",
    answer:
      "Your Life Blueprint is generated by an advanced AI model trained on thousands of authentic Bazi readings and classical texts. The AI calculates your birth chart (Four Pillars), analyzes the Five Element balance, identifies your Day Master (core energy type), maps your 10-year luck cycles, and synthesizes everything into a comprehensive, personalized report written in natural English. Every report is reviewed before delivery to ensure quality and positive framing.",
  },
  {
    question: "What information do I need to provide?",
    answer:
      "You'll need your birth date (day, month, year), your birth time (as precise as possible — even an estimate helps), and the city where you were born. The birth time is used for accurate chart calculation, as the Bazi system divides each day into 12 two-hour periods. If you don't know your exact birth time, you can select 'Unknown' and we'll use noon as a default.",
  },
  {
    question: "How long does it take to receive my report?",
    answer:
      "Your report is typically delivered to your email within 24 hours of purchase. Most reports are delivered much sooner — often within a few hours. You'll receive a confirmation email right after purchase, and the full report PDF will follow.",
  },
];

const testimonials = [
  {
    quote:
      "I was skeptical at first, but the Life Blueprint described my career struggles so accurately it gave me chills. The advice about timing my next career move was incredibly specific and helpful.",
    name: "Sarah M.",
    location: "Los Angeles, USA",
    product: "Life Blueprint",
  },
  {
    quote:
      "The Five Element analysis helped me understand why I clash with certain coworkers but vibe with others. It's like getting a user manual for yourself. The Year Ahead report correctly flagged a challenging period — I was prepared.",
    name: "James K.",
    location: "London, UK",
    product: "Life Blueprint + Year Ahead",
  },
  {
    quote:
      "I've tried Western astrology for years, but Bazi feels so much more specific and actionable. The monthly email forecasts from the Annual Pass keep me on track. Worth every penny.",
    name: "Emma R.",
    location: "Sydney, Australia",
    product: "Annual Pass",
  },
];

export default function HomePage() {
  return (
    <>
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-[#0f0f0f]">
        {/* 太极背景装饰 */}
        <div className="absolute inset-0 pointer-events-none z-0">
          <svg
            className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] opacity-[0.04]"
            viewBox="0 0 200 200"
            fill="none"
          >
            <circle cx="100" cy="100" r="98" stroke="#c8a951" strokeWidth="2" />
            <path
              d="M100 2 A98 98 0 0 1 100 198 A49 49 0 0 1 100 100 A49 49 0 0 0 100 2Z"
              fill="#c8a951"
            />
            <circle cx="100" cy="51" r="16" fill="#0f0f0f" />
            <circle cx="100" cy="149" r="16" fill="#c8a951" />
          </svg>
        </div>
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-gradient-to-br from-[#c8a951]/8 to-transparent blur-3xl pointer-events-none" />

        <div className="relative max-w-4xl mx-auto px-4 py-24 md:py-36 text-center z-10">
          <p className="text-[#c8a951] text-sm font-semibold uppercase tracking-[0.2em] mb-4">
            Ancient Wisdom · Modern Clarity
          </p>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight leading-tight mb-6 text-[#f0e6d3]">
            Discover Your{" "}
            <span className="text-gold">Life Blueprint</span>
            <br />
            with Ancient Chinese Wisdom
          </h1>
          <p className="text-lg md:text-xl text-[#9c9588] max-w-2xl mx-auto mb-10 leading-relaxed">
            Your birth date holds a map of your personality, career path,
            relationships, and life rhythm. Unlock it with AI-powered Bazi
            analysis — the world&apos;s oldest personality system, made for
            today.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/order?product=life-blueprint"
              className="px-8 py-4 btn-gold rounded-xl text-lg shadow-xl shadow-[#c8a951]/20"
            >
              Get Your Life Blueprint — $39.99
            </Link>
            <Link
              href="/order?product=year-ahead"
              className="px-8 py-4 bg-white/5 text-[#f0e6d3] rounded-xl font-semibold text-lg hover:bg-white/10 transition-all border border-[#2a2a2a]"
            >
              Try Year Ahead — $19.99
            </Link>
          </div>
          <p className="mt-6 text-xs text-[#9c9588]">
            Delivered within 24 hours · No account required · One-time payment
          </p>
        </div>
      </section>

      {/* Value Propositions */}
      <section className="py-20 md:py-28 bg-[#0f0f0f]">
        <div className="max-w-5xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] mb-4">
              Why People Are Discovering Their Bazi
            </h2>
            <p className="text-[#9c9588] max-w-xl mx-auto">
              A 1,000-year-old system, now powered by AI to give you clarity in
              a chaotic world.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {[
              {
                icon: (
                  <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                  </svg>
                ),
                title: "Deeply Personal",
                desc: "Unlike Western astrology, Bazi takes a completely different approach — it draws from your exact birth date, time, and place to reveal the elemental energies shaping who you are.",
              },
              {
                icon: (
                  <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                  </svg>
                ),
                title: "Practical Insights",
                desc: "Not vague horoscopes. Your report gives you concrete guidance on career timing, relationship patterns, and when to push forward versus when to hold back.",
              },
              {
                icon: (
                  <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                ),
                title: "Lifetime Value",
                desc: "Your chart stays with you forever. The Annual Pass keeps you updated with monthly forecasts aligned to your personal luck cycles — a compass that grows with you.",
              },
            ].map((vp, i) => (
              <div key={i} className="text-center">
                <div className="w-16 h-16 mx-auto mb-5 rounded-2xl bg-[#1a1a1a] text-[#c8a951] flex items-center justify-center border border-[#2a2a2a]">
                  {vp.icon}
                </div>
                <h3 className="text-lg font-bold text-[#f0e6d3] mb-2">{vp.title}</h3>
                <p className="text-sm text-[#9c9588] leading-relaxed">{vp.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-[#0a0a0a]">
        <div className="max-w-3xl mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] text-center mb-12">
            How It Works
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { step: "1", title: "Share Your Birth Info", desc: "Enter your birth date, time, and place. Takes less than 2 minutes." },
              { step: "2", title: "We Calculate Your Chart", desc: "Our AI computes your Four Pillars, Five Elements balance, and luck cycles." },
              { step: "3", title: "Receive Your Blueprint", desc: "Get your personalized 8000-word PDF report delivered to your inbox within 24 hours." },
            ].map((item) => (
              <div key={item.step} className="text-center">
                <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-[#c8a951] text-[#0f0f0f] font-bold text-lg flex items-center justify-center">
                  {item.step}
                </div>
                <h3 className="font-bold text-[#f0e6d3] mb-2">{item.title}</h3>
                <p className="text-sm text-[#9c9588]">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Product Cards */}
      <section className="py-20 md:py-28 bg-[#0f0f0f]" id="pricing">
        <div className="max-w-5xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] mb-4">
              Choose Your Reading
            </h2>
            <p className="text-[#9c9588] max-w-xl mx-auto">
              One-time payment. No subscription required (unless you want one).
              Delivered to your email within 24 hours.
            </p>
          </div>
          <ProductCards />
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] text-center mb-12">
            What Our Customers Say
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <TestimonialCard key={i} {...t} />
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Preview */}
      <section className="py-20 bg-[#0f0f0f]">
        <div className="max-w-2xl mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-[#f0e6d3] text-center mb-12">
            Common Questions
          </h2>
          <div>
            {faqs.map((faq, i) => (
              <FAQItem key={i} {...faq} />
            ))}
          </div>
          <div className="text-center mt-8">
            <Link href="/faq" className="text-[#c8a951] font-medium text-sm hover:text-[#d4b96a] transition-colors">
              View all questions →
            </Link>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 bg-[#0a0a0a] text-center relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none z-0">
          <svg
            className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] opacity-[0.03]"
            viewBox="0 0 200 200"
            fill="none"
          >
            <circle cx="100" cy="100" r="98" stroke="#c8a951" strokeWidth="2" />
            <path
              d="M100 2 A98 98 0 0 1 100 198 A49 49 0 0 1 100 100 A49 49 0 0 0 100 2Z"
              fill="#c8a951"
            />
            <circle cx="100" cy="51" r="16" fill="#0a0a0a" />
            <circle cx="100" cy="149" r="16" fill="#c8a951" />
          </svg>
        </div>
        <div className="max-w-2xl mx-auto px-4 relative z-10">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-[#f0e6d3]">
            Ready to Discover Your Blueprint?
          </h2>
          <p className="text-[#9c9588] mb-8 text-lg">
            Your birth chart contains wisdom that has guided people for over a
            thousand years. See what it reveals about you.
          </p>
          <Link
            href="/order?product=life-blueprint"
            className="inline-block px-8 py-4 btn-gold rounded-xl text-lg shadow-xl shadow-[#c8a951]/20"
          >
            Get Your Life Blueprint — $39.99
          </Link>
        </div>
      </section>
    </>
  );
}
